[package]
name = "exercises"
version = "0.1.0"
edition = "2024"

[lib]
name = "exercises"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.21.3"
log = "0.4.28"
